# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tfcuEoqtTOY54YnapjP1WPfmk4sv81O
"""

#!wget https://github.com/fmi-unibuc-ia/ia/blob/master/Data/images.zip

#!git clone https://github.com/fmi-unibuc-ia/ia

#!unzip './ia'

import numpy as np
import matplotlib.pyplot as plt
from skimage import io

p_list = [1,2,3]
n_array = np.array([1.0, 2.2, 3.4], dtype = np.float32)
print(p_list)
print(n_array)

print(n_array.dtype)

n_mat = np.array([[1, 2, 3],
                  [5, 6, 7]])

print(n_mat.shape)
print(n_mat[1, 2])
print(n_mat[1][2])
print(n_mat[1])

np.ones((2, 3))

np.zeros((2, 3))

np.eye(5)

np.full((3, 4), 9)

np.random.random((2, 3)) * 100

norm = np.random.normal(100, 15, (4, 5)).astype(np.int)

np.arange(0, 100, 5)

for i in [1, 4, 6]:
  print(i)

for idx, val in enumerate([1, 4, 6]):
  print(idx, val)

norm[:, 3:]

sub_norm = norm[1:3, 1:4]
sub_norm[0, 1] = 10000
print(sub_norm)
print(norm)

np.ravel(norm)

norm.flatten()

np.reshape(norm, (1, 20))

np.reshape(norm, (2, 10))

norm[[0, 1], [0, 1]]

sir = np.arange(0, 20)
sir

sir % 2 == 1

sir[[False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True]]

sir[sir > 10]

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x)
print(y)

x + y

x * y

x / y

np.sqrt(x)

np.power(x, 3)

np.matmul(x, y)

x.T

np.linalg.inv(x) # inversa

norm.shape

np.sum(norm)

np.sum(norm, axis = 0)

np.sum(norm, axis = 1)

np.sum(np.zeros((3, 4, 5)), axis = (1, 2)).shape

np.mean(np.zeros((3, 4, 5)), axis = (1, 2)).shape

x = np.arange(0, 3 * np.pi, 0.1) 
print(x)
y1 = np.sin(x)
print(y1)
y2 = np.cos(x)
print(y2)

plt.plot(x, y1, 'g')
plt.plot(x, y2, 'r')
plt.show()

plt.imshow(np.load('images/car_3.npy').astype(np.uint8), cmap = 'gray')

#1.a
imgs = np.array([np.load(r"images/car_{idx}.npy".format(idx = i)) for i in range(9) ])
print(imgs)

#1.b
suma = np.sum(imgs)
print(suma)

#1.c
sum_c = np.sum(imgs, axis = (1, 2))
print(sum_c)

#1.d
print(np.argmax(np.sum(imgs, axis=(1, 2))))

#1.e

io.imshow(mean_image.astype(np.uint8))
 
mean_image = np.mean(imgs, axis = 0)
io.imshow(mean_image.astype(np.uint8))
io.show()

#1.f
print(np.std(imgs))

#1.g
norm_imgs = (imgs - mean_image) / np.std(imgs)

#1.h
cropped = imgs[:, 200:301, 290:401]

plt.imshow(imgs[7].astype(np.uint), cmap = 'gray')

plt.imshow(cropped[7].astype(np.uint), cmap = 'gray')